### ISSUE TITLE
Boss “chance to spawn today” percentages seem off

### ISSUE THREAD

**Issue by mathiasbynens** [xandjiji/exevo-pan#141]
First off, nice work on the new boss tracker! It looks incredible and works great :) And I was excited to see you integrate our TibiaMaps.io mapper as well for the spawn locations ❤️ 

I did notice one potential issue: the “chance to spawn today” percentages seem surprisingly different from other sources. I tried a quick search but couldn't find how this is computed in this repository (maybe this part is closed source?). Perhaps if you could explain what you're doing I could give more specific input.

For example, Rukor Zad on [Vunira](https://www.exevopan.com/boss-tracker/Vunira) is listed as 21.31%, but [GuildStats currently lists it as 13.17%](https://guildstats.eu/bosses?world=Vunira&monsterName=Rukor%20Zad). (This is not to say that GuildStats has the correct number -- in fact, I made them aware of a flaw in their calculation back in October 2021, with a suggested corrected formula, but they haven't fixed it yet. Happy to share more details on this but perhaps this is easiest over email/Discord chat.)

What's the source of this difference? Is the % computation different from GuildStats, or is the historical kill stats data different, or both?

Thanks,
Mathias
TibiaMaps.io admin

**Comment by xandjiji** [comment]
hey there!

My data has came to distributions almost 1:1 similar to the distributions from GuildStats, but the chance calculation is definitely different

you can see the exact line responsible for calculating the boss chance for this specific case [here](https://github.com/xandjiji/exevo-pan/blob/master/apps/bazaar-scraper/src/Scripts/TrackBosses/tasks/calculateBossChances.ts#L81)
(I'm kinda embarrassed of this code because I couldn't find proper names for the math operations I am using in this code 😅)

in this case, Rukor Zad didn't show up in the expected range (which was 5\~10 days after it was last killed). We then consider that the boss was spawned but never killed. This means we should consider the next possible range which now could be from 10\~20 days. Our code is considering that this new range will have the same distribution shape as the 5\~10 days range, but "dilluted" across a 10\~20 range. Conceptually, I believe its the same as [this](https://i.imgur.com/XJf5ww0.png).

if the range would be missed again, we then just give up trying to estimate anything and force the chance to be unknown.

---

I would love any feedbacks because I really suck at math lol

**Comment by mathiasbynens** [comment]
The statistically accurate way to compute the chance, while taking the historical kill stats into account, is as follows.

GuildStats shows the kill frequency distribution based on the historical kill stats for e.g. [Dharalion on Vunira](https://guildstats.eu/bosses?world=Vunira&monsterName=Dharalion):

![](https://user-images.githubusercontent.com/81942/193623571-02607041-165c-49f4-ae78-1ea411cce001.png)

(I'm only referring to the GuildStats example because they show the chart + individual data per day, and I don't think know where to find the data you are using, else I would link to that directly.)

The actual chance of the boss spawning today can then be computed as follows:

```
actual chance = a priori chance of the boss spawning today / sum of a priori chances in remaining range including the current day
```

So for example, based on the GuildStats chart above, today is `day=7`, and `possibility=44.37%`. For tomorrow (`day=8`), `possibility=15.60%`, and for the day after (`day=9`), `possibility=0.00%`, and so on until (in this case) `day=14`. Feeding that into the formula, we get:

```
44.37% / (44.37% + 15.6% + 0.55% + 0.00% + 0.00% + 0.69% + 1.77% + 1.76%)
≈ 68.54%
```

I'm not sure if this matches what you're doing. It would be easier to confirm with access to your data :) (On that note, I've been publicly collecting kill stats since 2022-08-23 with the goal of having an open, shared dataset that fansites can use: https://github.com/tibiamaps/tibia-kill-stats)

**Comment by mathiasbynens** [comment]
A good way to test any implementation would be the following hypothetical scenario.

Imagine a boss with the following probabilities per day (based on historical kill stats data):

- probability on day 1 = 90%
- probability on day 2 = 5%
- probability on day 3 = 5%

We then get the following actual chances, based on the formula I provided:

- day 1 = 90% / (90% + 5% + 5%) = 90%
- day 2 = 5% / (5% + 5%) = 50%
- day 3 = 5% / 5% = 100%

Other ways of computing the percentage likely show incorrect results for at least one of these days. For example, the bug I reported to GuildStats means they would show the following incorrect chances:

- day 1 = 90% (happens to be correct)
- day 2 = 90% + 5% = 95% (wrong!)
- day 3 = 100% (happens to be correct)

Again, I haven't looked carefully at your implementation, and you might be doing everything correctly already -- in which case, just ignore me :)

**Comment by xandjiji** [comment]
> ```
> actual chance = a priori chance of the boss spawning today / sum of a priori chances in remaining range including the current day
> ```

yup, I'm doing this [already](https://github.com/xandjiji/exevo-pan/blob/master/apps/bazaar-scraper/src/Scripts/TrackBosses/tasks/utils.ts#L16).

I believe that the difference is only for cases where the boss was missed. Take a look at the difference in this case:
> Current Dharalion spawn chance on Zunera:
> GuildStats: 74.5%
> Exevo Pan: 22.24%

My calculation in this case is more pessimistic because it considers the possibility that Dharalion spawned on the 8th day, was missed, and then might respawn again on the 16th. I'm not sure about GuildStats, but I believe that they aren't considering this possibility because they don't have any data for Dharalion spawning after the 14th day.

**Comment by mathiasbynens** [comment]
Alright, awesome! Again, really nice work!
