### ISSUE TITLE
Boss count

### ISSUE THREAD

**Issue by brunominervino** [xandjiji/exevo-pan#159]
My team has killed the **_Fleabringer_** twice this week, and they remain high in all spots:

![image](https://user-images.githubusercontent.com/10432401/209941464-bdecd936-cdbb-47f4-b33a-43e458c7acb6.png)

**_The Voice of Ruin_** is having the same problem.

**Comment by xandjiji** [comment]
yeah, this happens for bosses that have a minimum respawn time of 1 day 😔

unfortunately, there is no way for us to tell if the boss was killed at `04:01 CET` or `03:59 CET` (being `04:00 CET` when the Tibia.com kill statistics page get updated). With this lack of information, we are not able to know exactly if at least 1 day has been passed since it was last killed. So we have to presume that it **can** spawn every day. And it gets worse by the fact that some of these bosses have multiple (and independent) spawns

Here is a list of bosses that fall into the same case:
- Apprentice Sheng
- Battlemaster Zunzu
- Cublarc the Plunderer
- Draptor
- Dreadmaw
- Fleabringer
- Munster
- Teleskor
- The Voice Of Ruin

**Comment by brunominervino** [comment]
Thank you @xandjiji
