### ISSUE TITLE
Winged Helmet is not in the list of rare items

### ISSUE THREAD

**Issue by Tschis** [xandjiji/exevo-pan#90]
There is an auction with Winged Helmet, but it does not show as a value to filter in the rare items select box

https://www.tibia.com/charactertrade/?subtopic=currentcharactertrades&page=details&auctionid=777821

**Comment by ricardo-cas** [comment]
Hey guys, i'll try to work on this issue.

**Comment by ricardo-cas** [comment]
Hey guys, i'll try to work on this feature ok? 
If you have any tips or more information about it, let me know on this thread.

**Comment by ricardo-cas** [comment]
@xandjiji i'm having troubles to setup the development env. Do you know how to fix this error? 
![image](https://user-images.githubusercontent.com/65743471/173255920-7777cdae-b227-46b3-af1d-bf892a61ab27.png)

**Comment by xandjiji** [comment]
you can see the full list of supported items [here](https://github.com/xandjiji/exevo-pan/blob/master/apps/bazaar-scraper/src/Scripts/ScrapRareItems/items.ts). Unfortunately, querying for "Winged Helmet" returns a lot of entries with the "rusty winged helmet" item. Since there isn't a lightweight method for filtering out there results, scraping for auctions with those items is not viable 😔
